language: node_js
node_js:
 - "10.15.1"
os: windows
env:
  - PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
    PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
    DB_HOST: ${DB_HOST}
    DB_NAME: ${DB_NAME}
    DB_CONTACT: ${DB_CONTACT}
    DB_SUBSCRIBE: ${DB_SUBSCRIBE}
    DB_REVIEW: ${DB_REVIEW}
    DB_ORDERS: ${DB_ORDERS}

branches:
  only:
  # - staging
  - master
deploy:
  # - provider: elasticbeanstalk
  #   access_key_id: ${AWS_ACCESS_KEY_ID}
  #   secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  #   region: "us-east-2"       
  #   app: "ecommerce_store"                     
  #   env: "ecommerce-store-staging"                     
  #   bucket_name: ${AWS_S3_BUCKET} 
  #   on:
  #     branch: "staging"

  - provider: elasticbeanstalk
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    region: "us-east-2"       
    app: "ecommerce_store"                     
    env: "ecommerce-store-prod"                     
    bucket_name: ${AWS_S3_BUCKET}
    on:
      branch: "master"

after_deploy:
  - echo "Application Deployed!"